### ISSUE TITLE
首页相关项目版本号颜色调整

### ISSUE THREAD

**Issue by shankerwangmiao** [loongson-community/areweloongyet#152]
目前首页在浅色模式时，各个项目的版本号的颜色过浅，难以辨认。

<img width="392" alt="image" src="https://github.com/loongson-community/areweloongyet/assets/6825907/761adb16-9afd-4955-9230-15838fbe4cc8">

**Comment by xry111** [comment]
```css
.project__goodSince_XZCG {
    color:var(--ifm-color-emphasis-200)
}
```

I'd change 200 to 500 (based on my experiment using the Inspector).
